version: "3.8"
services:
  api:
    container_name: "walrus-api"
    build:
      context: walrus-api
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: "walrus-postgres"
    image: "postgres:16"
    restart: always
    environment:
      - "POSTGRES_DB=walrus"
      - "POSTGRES_USER=app"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "app", "-d", "walrus" ]
      interval: 5s
      timeout: 60s
      retries: 5
